### PR TITLE
Fix hardcoded menu weight leading to conflict

### PR DESCRIPTION
**Pull request by pfigel**
Fixes an issue where the hardcoded summary action weight may cause conflicts with other extensions (e.g. `org.wikimedia.contacteditor`).

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks @pfigel

**Comment by bjendres** [comment]
@pfigel can you confirm that you're using this version (https://github.com/systopia/de.systopia.contactinactive/releases/tag/1.0-beta2) on CiviCRM 5.x? If so, I'll release a ``1.0`` version.

**Comment by pfigel** [comment]
@bjendres we're rolling this out on Friday, so if you want to be absolutely sure it works, next week would be good. 😁

**Comment by bjendres** [comment]
sure, I'll wait for your feedback

**Comment by pfigel** [comment]
@bjendres no one has complained yet, so I think this can be released.

**Pull request merged**
